# -*- coding: utf-8 -*-
"""iris_classification_hyperparameter_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TBrrjNzV4UnIX3L0UCdEy1CLO_7me1ks

# Iris Flower Classification using Hyperparameter Tuning

## Project Overview

This project demonstrates how hyperparameter tuning techniques can improve machine learning model performance using the famous Iris dataset.

The notebook compares baseline machine learning models and optimises a Support Vector Machine (SVM) using GridSearchCV and RandomizedSearchCV to identify the best hyperparameter combinations.
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""# 📂 Load Dataset

The Iris dataset is loaded directly from the Seaborn library. It contains measurements of iris flowers belonging to three different species.
"""

df = sns.load_dataset('iris')

"""# 🔍 Explore the Dataset

Inspect the dataset structure, preview records, and identify the target classes.
"""

df.head()

df['species'].unique()

from sklearn.model_selection import train_test_split

"""# ⚙️ Data Preparation

Separate the dataset into feature variables (X) and the target variable (y) before splitting into training and testing datasets.
"""

X = df.drop('species',axis = 1)
y = df['species']

"""# ✂️ Train-Test Split

Split the dataset into training and testing sets to evaluate model performance on unseen data.
"""

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

from sklearn.neighbors import KNeighborsClassifier

"""# 🤖 Train K-Nearest Neighbors (KNN)

Train a baseline K-Nearest Neighbors classifier and evaluate its accuracy.
"""

model_knn = KNeighborsClassifier(n_neighbors=13)

model_knn.fit(X_train,y_train)

model_knn.score(X_test,y_test)

"""# 🤖 Train Support Vector Machine (SVM)

Train a baseline Support Vector Machine classifier for comparison.
"""

from sklearn.svm import SVC

model_svm = SVC(gamma= 'auto')

model_svm.fit(X_train,y_train)

model_svm.score(X_test,y_test)

"""# 🔍 Hyperparameter Tuning using GridSearchCV

Perform an exhaustive search across different combinations of hyperparameters using cross-validation to identify the best-performing SVM configuration.
"""

#now lets use the grid search CV

from sklearn.model_selection import GridSearchCV

classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False)

classifier.fit(X,y)

"""# 📊 GridSearchCV Results

Review the cross-validation results and compare the performance of each hyperparameter combination.
"""

classifier.cv_results_

results = pd.DataFrame(classifier.cv_results_)

results

results[['param_C','param_kernel','mean_test_score']]

"""# 🎲 Hyperparameter Tuning using RandomizedSearchCV

Use RandomizedSearchCV to evaluate a random subset of hyperparameter combinations, reducing computational cost while searching for high-performing models.
"""

from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

classifier_r.fit(X,y)

"""# 📈 RandomizedSearchCV Results

Analyse the results obtained from RandomizedSearchCV and compare them with GridSearchCV.
"""

results = pd.DataFrame(classifier_r.cv_results_)

results

results[['param_C','param_kernel','mean_test_score']]

"""# ✅ Project Summary

## Summary

In this project, the Iris dataset was used to build and evaluate machine learning classification models.

The workflow included:

- Loading and exploring the dataset
- Preparing training and testing datasets
- Training baseline K-Nearest Neighbors and Support Vector Machine models
- Applying GridSearchCV for exhaustive hyperparameter tuning
- Applying RandomizedSearchCV for efficient hyperparameter optimisation
- Comparing model performance using cross-validation scores

This project demonstrates the importance of hyperparameter tuning in improving machine learning model performance while introducing two widely used optimisation techniques available in Scikit-learn.
"""

